import { Carousel, CarouselContainer, Container, Image, Section } from "./style";

export default function Home(props) {
	return (
		<Section>
			<Container>
				<CarouselContainer>
					<Carousel first="true">
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
					</Carousel>
					<Carousel>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
						<Image
							src="https://via.placeholder.com/480x270.webp/D0D0D0?text=◑﹏◐"
							alt="carousel-showcase"
						/>
					</Carousel>
				</CarouselContainer>
			</Container>
		</Section>
	);
}
